import type { Agent } from './gemini';
import { AGENTS } from './gemini';

export interface HandoffPlan {
  bizbotPipeline: 'v1';
  title: string;
  steps: { agentId: string; prompt: string }[];
}

export interface WorkflowShape {
  id: string;
  name: string;
  description: string;
  steps: { agentId: string; prompt: string }[];
}

const VALID_AGENT_IDS = new Set(AGENTS.map((a) => a.id));

function isHandoffPlan(x: unknown): x is HandoffPlan {
  if (!x || typeof x !== 'object') return false;
  const o = x as Record<string, unknown>;
  if (o.bizbotPipeline !== 'v1') return false;
  if (typeof o.title !== 'string' || !o.title.trim()) return false;
  if (!Array.isArray(o.steps) || o.steps.length === 0) return false;
  for (const s of o.steps) {
    if (!s || typeof s !== 'object') return false;
    const step = s as Record<string, unknown>;
    if (typeof step.agentId !== 'string' || !VALID_AGENT_IDS.has(step.agentId)) return false;
    if (typeof step.prompt !== 'string' || !step.prompt.trim()) return false;
  }
  return true;
}

/**
 * Looks for a ```json block containing { "bizbotPipeline": "v1", ... } in an assistant message.
 */
export function parseHandoffPlanFromMessage(content: string): HandoffPlan | null {
  const fence =
    /```(?:json)?\s*([\s\S]*?)```/gi;
  let m: RegExpExecArray | null;
  while ((m = fence.exec(content)) !== null) {
    const raw = m[1]?.trim();
    if (!raw) continue;
    try {
      const parsed = JSON.parse(raw) as unknown;
      if (isHandoffPlan(parsed)) return parsed;
    } catch {
      /* continue */
    }
  }
  return null;
}

export function handoffPlanToWorkflow(plan: HandoffPlan): WorkflowShape {
  return {
    id: `handoff-${Date.now()}`,
    name: plan.title.trim(),
    description: 'Generated by Router — multi-agent handoff',
    steps: plan.steps.map((s) => ({
      agentId: s.agentId,
      prompt: s.prompt.trim(),
    })),
  };
}

/** One-click pipelines from the dashboard (no Router JSON required). */
export const BUILTIN_WORKFLOWS: WorkflowShape[] = [
  {
    id: 'builtin-launch-kit',
    name: 'Product launch pipeline',
    description: 'Strategy → project plan → social copy → SEO angles',
    steps: [
      {
        agentId: 'strategy-advisor',
        prompt:
          'User goal: {{input}}\n\nGive a concise strategic outline: positioning, risks, and 3 priorities. End with clear bullets the next agents can use.',
      },
      {
        agentId: 'project-manager',
        prompt:
          'Prior strategy output:\n{{previous}}\n\nBreak this into a dated task list with owners mapped to BizBot agents (use real agent names only).',
      },
      {
        agentId: 'social-media',
        prompt:
          'Strategy + plan context:\n{{all_previous}}\n\nWrite 3 feed posts + hashtags for Instagram/LinkedIn aligned to the launch.',
      },
      {
        agentId: 'seo-strategist',
        prompt:
          'Full context so far:\n{{all_previous}}\n\nSuggest 5 SEO-friendly page titles and primary keywords for the launch.',
      },
    ],
  },
  {
    id: 'builtin-social-from-photos',
    name: 'Photos → commercial kit',
    description: 'Producer specs + captions (attach images to the first message)',
    steps: [
      {
        agentId: 'commercial-producer',
        prompt:
          'User request: {{input}}\n\nImages are attached. Output ASPECT and CAPTION lines as required, plus platform recommendations.',
      },
      {
        agentId: 'social-media',
        prompt:
          'Commercial producer output:\n{{previous}}\n\nRefine short captions + hashtag sets for IG + TikTok.',
      },
    ],
  },
  {
    id: 'builtin-social-mini',
    name: 'Social Media Mini Workflow',
    description: 'Quick angle → platform-ready posts and hashtags',
    steps: [
      {
        agentId: 'strategy-advisor',
        prompt:
          'User goal or topic: {{input}}\n\nIn 5–8 bullet points, give messaging angles and audience hooks the social step can use. Stay concise.',
      },
      {
        agentId: 'social-media',
        prompt:
          'Strategy context:\n{{all_previous}}\n\nProduce 3 distinct social posts (Instagram, LinkedIn, TikTok) with captions, visual ideas, and hashtags. Align with the angles above.',
      },
    ],
  },
];
